name: renv_nifh
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-tidyverse
  - r-patchwork
  - r-languageserver
  - r-rmarkdown
  - r-httpgd
  - bioconductor-biostrings
  - radian
  - snakemake
  - pip =23.3.1
  - pandas =2.1.2
