name: renv_data_genomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-tidyverse
  - r-patchwork
  - r-languageserver
  - r-rmarkdown
  - r-httpgd
  - r-dslabs
  - r-biocmanager
  - bioconductor-genefilter
  # - bioconductor-genefilter
  - radian
  - python
  - pandas
  - numpy
  - AnnotationHub
  - Biobase
  - cluster
  - erma
  - GenomeInfoDb
  - GenomicAlignments
  - GenomicFeatures
  - GenomicRanges
  - genomicsclass/ERBS
  - genomicsclass/tissuesGeneExpression
  - ggbio
  - Gviz
  - hgu133a.db
  - Homo.sapiens
  - knitr
  - org.Dm.eg.db
  - org.Hs.eg.db
  - pasillaBamSubset
  - RNAseqData.HNRNPC.bam.chr14
  - Rsamtools
  - rtracklayer
  - scales
  - shiny
  - Sushi
  - TxDb.Dmelanogaster.UCSC.dm3.ensGene
  - TxDb.Hsapiens.UCSC.hg19.knownGene
