name: renv_data_genomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-tidyverse
  - r-patchwork
  - r-languageserver
  - r-rmarkdown
  - r-httpgd
  - r-dslabs
  - r-biocmanager
  - bioconductor-genefilter
  # - bioconductor-genefilter
  - radian
  - python
  - pandas
  - numpy
