name: renv
channels:
  - conda-forge
  - bioconda
dependencies:
  # - r-base
  # - r-tidyverse
  - r-essentials # This has both r-base and r-tidyverse
  - r-patchwork
  - r-roxygen2
  - r-languageserver
  - r-rmarkdown
  - r-httpgd
  - radian
  - snakemake
